### ISSUE TITLE
Twig partials example

### ISSUE THREAD

**Issue by mgunia-gog** [jabney/render-template-loader-demo#2]
Hey,
Do you think it would be possible to have partials support for twig templates (include)?

**Comment by jabney** [comment]
This has been addressed in `render-template-loader` `v1.0.1`.  See this [test](https://github.com/jabney/render-template-loader/blob/master/test/twig.spec.js).

Here's how to make it work:

Configure the `path` option in the `engineOptions` function:

```javascript
const options = {
    engine: 'twig',
    locals: {
      title: 'Twig Template',
      desc: 'A template rendered by Twig'
    },
    engineOptions: function (info) {
      return { path: info.filename }
    }
  }
```

The `path` configuration will set up `twig` to look for partials relative to the source template directory. 

Specify the partial path relative to the source template:

```html
<h1>{{ title }}</h1>
{% include 'partials/desc.twig' %}
```
